pipeline {
    agent any

    parameters {
        booleanParam(name: 'autoApprove', defaultValue: false, description: 'Automatically run apply after generating plan?')
        choice(name: 'action', choices: ['apply', 'destroy'], description: 'Select the action to perform')
    }

    environment {
        AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        TF_DIR = 'Terraform-jenkins-app/T-Scripts'  // Define your Terraform directory here
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/veerababu5/Terraform.git'
            }
        }
        
        stage('Terraform init') {
            steps {
                dir(env.TF_DIR) {  // Change to Terraform directory
                    sh 'terraform init'
                }
            }
        }
        
        stage('Plan') {
            steps {
                dir(env.TF_DIR) {
                    sh 'terraform plan -out tfplan'
                    sh 'terraform show -no-color tfplan > tfplan.txt'
                    archiveArtifacts artifacts: 'tfplan.txt'  // Save plan for reference
                }
            }
        }
        
        stage('Apply / Destroy') {
            steps {
                script {
                    dir(env.TF_DIR) {
                        if (params.action == 'apply') {
                            if (!params.autoApprove) {
                                def plan = readFile 'tfplan.txt'
                                input message: "Do you want to apply the plan?",
                                parameters: [text(name: 'Plan', description: 'Please review the plan', defaultValue: plan)]
                            }
                            sh 'terraform apply -input=false tfplan'
                        } else if (params.action == 'destroy') {
                            // Extra confirmation for destroy
                            if (!params.autoApprove) {
                                input message: "WARNING: This will DESTROY all infrastructure. Confirm?",
                                parameters: [booleanParam(name: 'confirm', defaultValue: false)]
                            }
                            sh 'terraform destroy -auto-approve'
                        } else {
                            error "Invalid action selected"
                        }
                    }
                }
            }
        }
    }
    
    post {
        always {
            cleanWs()  // Clean up workspace
        }
    }
}
